module.exports={
	devServer:{
		host:'localhost',
		port:8080,
		proxy:{
			'/api':{
				target:'http://mall-pre.springboot.cn',
				changeOrigin:true,//proxy的changeOrigin是false：请求头中host仍然是浏览器发送过来的host；如果设置成true：发送请求头中host会设置成target。
				pathRewrite:{
					'/api':''
				}
			}
		}
	}
}